<?php
$benefits = array('the benefit of'   => array('humanity',
                                              'children',
                                              'animals',
                                              'transportation',
                                              'the environment',
                                              'non profits',
                                              'peace',
                                              'someone else',
                                              'a group of people',
                                              'the open source community',
                                              'your local community',
                                              'schools',
                                              'shelter animals',
                                              'coworking spaces',
                                              'the homeless'),
                  'the good of'         => array('the world'),
                  'making'          => array('piles of cash'),
                  'selling'         => array('products',
                                             'software',
                                             'devices',
                                             'hardware',
                                             'goods',
                                             'services'),
                  'random'          => array('business',
                                             'yourself',
                                             'a niche market',
                                             'selling products',
                                             '[whatever you want]'));

$subject = array('water', 
                  'food', 
                  'air', 
                  'energy', 
                  'travel', 
                  'sports', 
                  'money', 
                  'business', 
                  'news', 
                  'startups', 
                  'clothing', 
                  'women', 
                  'men', 
                  'parenthood', 
                  'fun', 
                  'games', 
                  'body piercings',
                  'cars', 
                  'airplanes', 
                  'animals', 
                  'furniture', 
                  'fashion', 
                  'shoes', 
                  'hats', 
                  'jokes or humor', 
                  'web comics',
                  'tv', 
                  'movies', 
                  'the internet', 
                  'recipes', 
                  'apps', 
                  'websites', 
                  'automation', 
                  'streamlining', 
                  'pivoting an idea or project', 
                  'dancing', 
                  'singing', 
                  'colors', 
                  'crime', 
                  'good deeds', 
                  'fire', 
                  'North America', 
                  'Africa', 
                  'Asia', 
                  'Europe', 
                  'Australia', 
                  'startups', 
                  'South America', 
                  'houses', 
                  'decor',
                  'gender equality',
                  '[insert your own subject]',
                  '[crowd decided subject]');

$type = array('a mobile app', 
               'a web app',  
               'a data filtering app',
               'something',
               'a social app',
               'a location based app',
               'a game',
               'a news app',
               '[type of app]',
               'a review app',
               'an aggregator',
               'travel site');


?>